import { TypographyOptions } from '@mui/material/styles/createTypography';

const defaultFont = `"Work Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif`;

const fonts = {
	default: defaultFont,
	h1: `"Fredericka the Great", ${defaultFont}`,
	h2: `Mali, ${defaultFont}`,
	h3: `Flamenco, ${defaultFont}`,
	h4: `"Playwrite VN", ${defaultFont}`,
	h5: `"Playwrite AR", ${defaultFont}`,
	h6: `"Playwrite PE", ${defaultFont}`,
};

export const typography: TypographyOptions = {
	htmlFontSize: 16,
	fontFamily: fonts.default,
	fontSize: 14,
	fontWeightLight: 300,
	fontWeightRegular: 400,
	fontWeightMedium: 500,
	fontWeightBold: 700,
	h1: {
		fontFamily: fonts.h1,
		fontWeight: 300,
		fontSize: '3.5rem',
		lineHeight: 1.167,
		letterSpacing: '-0.01562em',
		color: "#eeff41",
	},
	h2: {
		fontFamily: fonts.h2,
		fontWeight: 300,
		fontSize: '3.25rem',
		lineHeight: 1.2,
		letterSpacing: '-0.00833em',
	},
	h3: {
		fontFamily: fonts.h3,
		fontWeight: 400,
		fontSize: '3rem',
		lineHeight: 1.167,
		letterSpacing: '0em',
	},
	h4: {
		fontFamily: fonts.h4,
		fontWeight: 400,
		fontSize: '2.125rem',
		lineHeight: 1.235,
		letterSpacing: '0.00735em',
	},
	h5: {
		fontFamily: fonts.h5,
		fontWeight: 400,
		fontSize: '1.5rem',
		lineHeight: 1.334,
		letterSpacing: '0em',
	},
	h6: {
		fontFamily: fonts.h6,
		fontWeight: 500,
		fontSize: '1.25rem',
		lineHeight: 1.6,
		letterSpacing: '0.0075em',
	},
	subtitle1: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '1rem',
		lineHeight: 1.75,
		letterSpacing: '0.00938em',
	},
	subtitle2: {
		fontFamily: fonts.default,
		fontWeight: 500,
		fontSize: '0.875rem',
		lineHeight: 1.57,
		letterSpacing: '0.00714em',
	},
	body1: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '1rem',
		lineHeight: 1.5,
		letterSpacing: '0.00938em',
	},
	body2: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '0.875rem',
		lineHeight: 1.43,
		letterSpacing: '0.01071em',
	},
	button: {
		fontFamily: fonts.default,
		fontWeight: 500,
		fontSize: '0.875rem',
		lineHeight: 1.75,
		letterSpacing: '0.02857em',
		textTransform: 'uppercase',
	},
	caption: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '0.75rem',
		lineHeight: 1.66,
		letterSpacing: '0.03333em',
	},
	overline: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '0.75rem',
		lineHeight: 2.66,
		letterSpacing: '0.08333em',
		textTransform: 'uppercase',
	},
};
