import { TypographyOptions } from '@mui/material/styles/createTypography';
import { darkTextColors, TextColors } from './colors';

const defaultFont = `"Work Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif`;

const fonts = {
	default: defaultFont,
	h1: `"Fredericka the Great", ${defaultFont}`,
	h2: `Mali, ${defaultFont}`,
	h3: `Flamenco, ${defaultFont}`,
	h4: `"Playwrite VN", ${defaultFont}`,
	h5: `"Playwrite AR", ${defaultFont}`,
	h6: `"Playwrite PE", ${defaultFont}`,
	code: `"JetBrains Mono", Inconsolata, "Courier Prime", "Courier New", Courier, monospace`,
	headings: `"Playpen Sans", "Flamenco", "Edu SA Beginner", "Fredericka the Great", "Itim", ${defaultFont}`,
	strong: `"Playpen Sans", "Playwrite DE Grund", "Itim", ${defaultFont}`,
};

export const createTypographyWithColors = (colors: TextColors | undefined = darkTextColors): TypographyOptions => ({
	htmlFontSize: 16,
	fontFamily: fonts.default,
	fontSize: 14,
	fontWeightLight: 300,
	fontWeightRegular: 400,
	fontWeightMedium: 500,
	fontWeightBold: 700,
	h1: {
		color: colors.h1,
		fontFamily: fonts.h1,
		fontWeight: 300,
		fontSize: '3.5rem',
		lineHeight: 1.167,
		letterSpacing: '-0.01562em',
	},
	h2: {
		color: colors.h2,
		fontFamily: fonts.h2,
		fontWeight: 300,
		fontSize: '3.25rem',
		lineHeight: 1.35,
		letterSpacing: '-0.00833em',
	},
	h3: {
		color: colors.h3,
		fontFamily: fonts.h3,
		fontWeight: 400,
		fontSize: '3.25rem',
		lineHeight: 1.5,
		letterSpacing: '0em',
	},
	h4: {
		color: colors.h4,
		fontFamily: fonts.h4,
		fontWeight: 400,
		fontSize: '2rem',
		lineHeight: 1.75,
		letterSpacing: '0.00735em',
	},
	h5: {
		color: colors.h5,
		fontFamily: fonts.h5,
		fontWeight: 400,
		fontSize: '1.75rem',
		lineHeight: 2.125,
		letterSpacing: '0em',
	},
	h6: {
		color: colors.h6,
		fontFamily: fonts.h6,
		fontWeight: 500,
		fontSize: '1.5rem',
		lineHeight: 1.5,
		letterSpacing: '0.0075em',
	},
	subtitle1: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '1rem',
		lineHeight: 1.75,
		letterSpacing: '0.00938em',
	},
	subtitle2: {
		fontFamily: fonts.default,
		fontWeight: 500,
		fontSize: '0.875rem',
		lineHeight: 1.57,
		letterSpacing: '0.00714em',
	},
	body1: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '1rem',
		lineHeight: 1.5,
		letterSpacing: '0.00938em',
	},
	body2: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '0.875rem',
		lineHeight: 1.43,
		letterSpacing: '0.01071em',
	},
	button: {
		fontFamily: fonts.strong,
		fontWeight: 500,
		fontSize: '1rem',
		lineHeight: 1.5,
		letterSpacing: '0.05em',
		textTransform: 'capitalize',
	},
	caption: {
		fontFamily: fonts.default,
		fontWeight: 400,
		fontSize: '0.75rem',
		lineHeight: 1.66,
		letterSpacing: '0.03333em',
	},
	overline: {
		fontFamily: fonts.headings,
		fontWeight: 400,
		fontSize: '0.75rem',
		lineHeight: 2.66,
		letterSpacing: '0.08333em',
		textTransform: 'capitalize',
	},
});
